server:
  port: 9002
  servlet:
    context-path: /college
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college?allowPublicKeyRetrieval=true&&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: SIMPLE
logging:
  file:
    name: college.log
